export interface Palette {
  key: string;
  name: string;
  description: string;
  tags: string[];
  // All values feed into CSS vars + BrandTokens
  accent: string;
  accentHover: string;
  accentSoft: string;
  accentInk: string;
  accentOnAccent: string;
  heroOverlayStart: string;
  heroOverlayMid: string;
  heroOverlayEnd: string;
  // Font pair suggestion
  fontHeading: string;
  fontBody: string;
}

export const PALETTES: Palette[] = [
  {
    key: "slate-orange",
    name: "Slate & Orange",
    description: "Confident and grounded. Works across all trades.",
    tags: ["builders", "roofing", "general"],
    accent: "#EA580C",
    accentHover: "#C2410C",
    accentSoft: "#FFF1E8",
    accentInk: "#C2410C",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(30,41,59,0.90)",
    heroOverlayMid: "rgba(30,41,59,0.65)",
    heroOverlayEnd: "rgba(30,41,59,0.10)",
    fontHeading: "'DM Serif Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "navy-gold",
    name: "Navy & Gold",
    description: "Premium and established. Ideal for long-standing businesses.",
    tags: ["plumbing", "heating", "electrical", "joinery"],
    accent: "#B8860B",
    accentHover: "#8B6508",
    accentSoft: "#FDF8EC",
    accentInk: "#8B6508",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(15,39,68,0.92)",
    heroOverlayMid: "rgba(15,39,68,0.68)",
    heroOverlayEnd: "rgba(15,39,68,0.10)",
    fontHeading: "'DM Serif Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "forest-lime",
    name: "Forest & Lime",
    description: "Natural and vibrant. Perfect for landscaping and garden trades.",
    tags: ["landscaping", "garden", "tree surgery"],
    accent: "#65A30D",
    accentHover: "#4D7C0F",
    accentSoft: "#F1F8E6",
    accentInk: "#4D7C0F",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(20,52,27,0.91)",
    heroOverlayMid: "rgba(20,52,27,0.65)",
    heroOverlayEnd: "rgba(20,52,27,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "charcoal-red",
    name: "Charcoal & Red",
    description: "Bold and direct. Stops people in their tracks.",
    tags: ["electrical", "plumbing", "emergency", "gas"],
    accent: "#DC2626",
    accentHover: "#B91C1C",
    accentSoft: "#FEF2F2",
    accentInk: "#B91C1C",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(17,17,17,0.93)",
    heroOverlayMid: "rgba(17,17,17,0.68)",
    heroOverlayEnd: "rgba(17,17,17,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "midnight-cyan",
    name: "Midnight & Cyan",
    description: "Modern and technical. Great for electrical and tech-forward trades.",
    tags: ["electrical", "solar", "smart home", "CCTV"],
    accent: "#0891B2",
    accentHover: "#0E7490",
    accentSoft: "#EFF9FB",
    accentInk: "#0E7490",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(2,6,23,0.93)",
    heroOverlayMid: "rgba(2,6,23,0.68)",
    heroOverlayEnd: "rgba(2,6,23,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "stone-amber",
    name: "Stone & Amber",
    description: "Warm and reliable. Suits roofing, stonework, and bricklaying.",
    tags: ["roofing", "masonry", "bricklaying", "builders"],
    accent: "#D97706",
    accentHover: "#B45309",
    accentSoft: "#FFFBEB",
    accentInk: "#B45309",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(41,37,36,0.90)",
    heroOverlayMid: "rgba(41,37,36,0.65)",
    heroOverlayEnd: "rgba(41,37,36,0.08)",
    fontHeading: "'DM Serif Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "racing-green",
    name: "Racing Green",
    description: "British quality signalling. Works for premium trades.",
    tags: ["joinery", "glazing", "landscaping", "builders"],
    accent: "#15803D",
    accentHover: "#166534",
    accentSoft: "#F0FDF4",
    accentInk: "#166534",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(5,46,22,0.92)",
    heroOverlayMid: "rgba(5,46,22,0.66)",
    heroOverlayEnd: "rgba(5,46,22,0.08)",
    fontHeading: "'DM Serif Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "teal-white",
    name: "Teal & White",
    description: "Clean and trustworthy. Ideal for plumbing and heating.",
    tags: ["plumbing", "heating", "gas", "boilers"],
    accent: "#0F766E",
    accentHover: "#0D6460",
    accentSoft: "#EFFEFB",
    accentInk: "#0D6460",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(19,78,74,0.91)",
    heroOverlayMid: "rgba(19,78,74,0.65)",
    heroOverlayEnd: "rgba(19,78,74,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "burgundy-sand",
    name: "Burgundy & Sand",
    description: "Craft and character. Beautiful for joinery and carpentry.",
    tags: ["joinery", "carpentry", "furniture", "fitted kitchens"],
    accent: "#9F1239",
    accentHover: "#881337",
    accentSoft: "#FFF1F2",
    accentInk: "#881337",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(67,20,7,0.91)",
    heroOverlayMid: "rgba(67,20,7,0.66)",
    heroOverlayEnd: "rgba(67,20,7,0.08)",
    fontHeading: "'DM Serif Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "graphite-yellow",
    name: "Graphite & Yellow",
    description: "High-vis and no-nonsense. Tradesmen who get things done.",
    tags: ["gas", "heating", "electrical", "construction"],
    accent: "#CA8A04",
    accentHover: "#A16207",
    accentSoft: "#FEFCE8",
    accentInk: "#A16207",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(17,24,39,0.93)",
    heroOverlayMid: "rgba(17,24,39,0.68)",
    heroOverlayEnd: "rgba(17,24,39,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "black-copper",
    name: "Black & Copper",
    description: "Sleek and premium. Stands out from every competitor.",
    tags: ["plumbing", "heating", "electrical", "premium"],
    accent: "#B45309",
    accentHover: "#92400E",
    accentSoft: "#FFF7ED",
    accentInk: "#92400E",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(3,7,18,0.94)",
    heroOverlayMid: "rgba(3,7,18,0.70)",
    heroOverlayEnd: "rgba(3,7,18,0.10)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "steel-blue",
    name: "Steel Blue",
    description: "Solid and dependable. Works for any trade that values trust.",
    tags: ["builders", "roofing", "scaffolding", "structural"],
    accent: "#1D4ED8",
    accentHover: "#1E40AF",
    accentSoft: "#EFF6FF",
    accentInk: "#1E40AF",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(15,23,42,0.92)",
    heroOverlayMid: "rgba(15,23,42,0.66)",
    heroOverlayEnd: "rgba(15,23,42,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "cream-terracotta",
    name: "Cream & Terracotta",
    description: "Warm and artisanal. Great for plastering and decorating.",
    tags: ["plastering", "decorating", "painting", "tiling"],
    accent: "#C2410C",
    accentHover: "#9A3412",
    accentSoft: "#FFF7F0",
    accentInk: "#9A3412",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(55,33,21,0.89)",
    heroOverlayMid: "rgba(55,33,21,0.62)",
    heroOverlayEnd: "rgba(55,33,21,0.08)",
    fontHeading: "'DM Serif Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
  {
    key: "purple-silver",
    name: "Purple & Silver",
    description: "Distinctive and premium. For trades that want to stand apart.",
    tags: ["bathroom", "kitchen", "premium renovation", "fitted"],
    accent: "#7C3AED",
    accentHover: "#6D28D9",
    accentSoft: "#F5F3FF",
    accentInk: "#6D28D9",
    accentOnAccent: "#FFFFFF",
    heroOverlayStart: "rgba(30,22,54,0.92)",
    heroOverlayMid: "rgba(30,22,54,0.66)",
    heroOverlayEnd: "rgba(30,22,54,0.08)",
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
  },
];

export const PALETTE_MAP: Record<string, Palette> = Object.fromEntries(
  PALETTES.map((p) => [p.key, p])
);

export const DEFAULT_PALETTE = PALETTES[0];
